# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171010_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
    ]
